name = "altbet"
compatibility_date = "2025-10-30"
main = "./dist/server.js"

[vars]
NODE_ENV = "production"

[[vars]]
DATABASE_URL="postgresql://neondb_owner:npg_0txn6PuUXkYG@ep-plain-feather-a2i5bich-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
DIRECT_URL="postgresql://neondb_owner:npg_0txn6PuUXkYG@ep-plain-feather-a2i5bich-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
